meta_product_name: "Le vide grenier"
meta_title: "Le vide grenier - Commerce d'oeuvres d'art"
meta_description: "Le vide grenier est une plateforme de vente d'ouvres d'art en ligne. Venez découvrir les artistes talentueux de demain."
meta_image: "cover.png" # should exist in `app/assets/images/`
